/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meditracker;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    private Stage stage;
    public void start(Stage primaryStage) throws Exception{
        
        stage = primaryStage;      
        stage.show();

    }
}
